Question 1

Write a Python program to convert an array to an ordinary list with the same items.

We can use the np.tolist() function.

In [16]:
import numpy as np
Ls=[input("Donner un élément : ") for i in range (int(input("Donner la taille  : ")))]
T=np.array(Ls)
print(T)
Lf=T.tolist()
print(Lf)

['1' '2' '3' '4' '5']
['1', '2', '3', '4', '5']


Question 2 

Write a NumPy program to compute the sum of the diagonal elements of a given array.

Hint: There are two possible methods to solve this problem: 

Manually (without direct function). 
Using the trace function

In [46]:
import numpy as np
nc=int(input("Donner le nombre des colonne  : "))
nl=int(input("Donner le nombre des lignes  : "))
ls=[[float(input("Donner un nombre : ")) for i in range (nc) ] for j in range (nl)]
T=np.array(ls)
print(T)
D=0
for x in range (nc) :
    for y in range (nl) :
        if x==y:
            D=D+T[x,y]       
print(D)     

[[1. 2. 3.]
 [4. 5. 6.]
 [1. 2. 3.]]
9.0


In [49]:
import numpy as np
nc=int(input("Donner le nombre des colonne  : "))
nl=int(input("Donner le nombre des lignes  : "))
ls=[[float(input("Donner un nombre : ")) for i in range (nc) ] for j in range (nl)]
T=np.array(ls)
print(T)
D=np.trace(T)     
print(D)     

[[4. 3.]
 [2. 4.]]
8.0


Question 3

Given an array of your choice, get all the values higher than X:

If a = [[1,2],[3,5]] and x = 2 :  then 3 and 5 are higher than 2. 

In [ ]:
import numpy as np
nc=int(input("Donner le nombre des colonne  : "))
nl=int(input("Donner le nombre des lignes  : "))
ls=[[float(input("Donner un nombre : ")) for i in range (nc) ] for j in range (nl)]
T=np.array(ls)
print(T)
x=int(input("Donner un X : "))
for a in range (nc) :
    for b in range (nl) :
        if x < T[a,b]:
            print(f"{T[a,b]} are higher than {x}")


Question 4

Given two arrays, A & B have the same shape. 

The task is to apply addition by hand: C is the new array. 



In [ ]:
import numpy as np
nc1=int(input("Donner le nombre des colonne de array 1 : "))
nl1=int(input("Donner le nombre des lignes de array 1 : "))
ls1=[[float(input("Donner un nombre : ")) for i in range (nc1) ] for j in range (nl1)]
T1=np.array(ls1)
print(T1)
nc2=int(input("Donner le nombre des colonne de array 2 : "))
nl2=int(input("Donner le nombre des lignes de array 2 : "))
ls2=[[float(input("Donner un nombre : ")) for i in range (nc2) ] for j in range (nl2)]
T2=np.array(ls2)
print(T2)

T3=np.array([[T1[a,b]+T2[a,b] for a in range(nc2)] for b in range(nl1)])
print(T3)

Question 5

Write a NumPy program to subtract the mean of each row of a given matrix.

Hint: use the mean function

In [22]:
import numpy as np
nc1=int(input("Donner le nombre des colonne de array 1 : "))
nl1=int(input("Donner le nombre des lignes de array 1 : "))
M=S=0
ls1=[[float(input("Donner un nombre : "))   for i in range (nc1) ] for j in range (nl1)]
T1=np.array(ls1)
print(T1)
T2=np.array([[ T1[j,i]-T1[j,:].mean()   for i in range (nc1) ] for j in range (nl1)] )       
print(T2)


[[3. 3.]
 [2. 1.]]
[[ 0.   0. ]
 [ 0.5 -0.5]]
